version: '3'
services:
    app:
        image: stockbuster
        container_name: stockbuster
        volumes:
            - './Backend:/app'
        ports:
            - '3000:3000'
        environment:
      - MONGO_HOST=mongodb_service
      - MONGO_PORT=27017
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

            - CHOKIDAR_USEPOLLING=true
        restart: always
mongodb_service:
    image: mongo
    container_name: mongodb_service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    restart: always
    volumes:
      - mongodb_service:/data/db

volumes:
  mongodb_service:
