version: '3'
services:
    app:
        image: stockbuster
        container_name: stockbuster
        volumes:
            - './Backend:/app'
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
            - COMPOSE_CONVERT_WINDOWS_PATHS=1
        restart: always
