services:
    frontend:
        build: ./frontend
        container_name: stockbuster-frontend
        volumes:
            - './Frontend:/app'
        ports:
            - '8080:8080'
        environment:
            - CHOKIDAR_USEPOLLING=true
        restart: always
    backend:
        build: ./backend
        container_name: stockbuster-backend
        depends_on:
            - mysql
        volumes:
            - './Backend:/app'
        ports:
            - '3000:3000'
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USERNAME=${MYSQL_USERNAME}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - CHOKIDAR_USEPOLLING=true
        restart: always
    mysql:
        image: mysql:9.1
        container_name: stockbuster-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USERNAME}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always
        volumes:
            - mysql_data:/data/db

volumes:
    mysql_data:
